#!/usr/bin/env python3
"""Ensure strong runtime interpolation secrets exist in .env.secrets.

Postgres / Redis / MinIO root credentials are interpolated by ``docker compose``
at ``up`` time (``${VAR:-default}``). When a key is absent, compose silently
falls back to the WEAK dev default (``localdev`` / no Redis auth / ``facilminio``)
— which is exactly the hardening gap this closes.

This idempotently generates a strong value for each MISSING key and appends it
to ``.env.secrets``. Existing keys are NEVER modified, so values stay stable
across runs (and a recreate re-uses the same strong passwords).

Usage
-----
    python deploy/scripts/ensure_secrets.py            # default .env.secrets
    python deploy/scripts/ensure_secrets.py --path X   # custom file

Exit codes
----------
0  Secrets present (some may have been generated — see stdout).
1  I/O error.
"""

from __future__ import annotations

import argparse
import secrets
import sys
from pathlib import Path

# Runtime secrets that docker compose interpolates into the data-plane services.
# JWT_SECRET_KEY is the CANONICAL JWT signing-key name across the framework
# (init.py / secrets manifest / .env.secrets / the backend provider). It used to
# read JWT_SECRET here, generating a *second*, unrelated secret — fixed so the
# backend signs with the same key the deploy provisions.
RUNTIME_SECRETS = ("POSTGRES_PASSWORD", "REDIS_PASSWORD", "MINIO_ROOT_PASSWORD",
                   "ADMIN_TOKEN", "JWT_SECRET_KEY",
                   # TOTP secret-at-rest encryption key. Read by the backend
                   # (app.security.crypto) and REQUIRED distinct in production
                   # (SEC-008) — generate it like JWT_SECRET_KEY so a --apply that
                   # skipped the wizard still satisfies the prod requirement (A3).
                   "TOTP_ENCRYPTION_KEY",
                   # Keycloak admin bootstrap password (compose interpolates it;
                   # the keycloak provisioner reads it). Auto-generated so prod
                   # never falls back to the weak `:-admin` compose default.
                   "KEYCLOAK_ADMIN_PASSWORD",
                   # OpenBao dev root token — the keystone credential. Auto-generated
                   # so it is NEVER the guessable literal `root` (SEC-001).
                   "OPENBAO_DEV_ROOT_TOKEN")


def _parse(path: Path) -> dict[str, str]:
    """Minimal dotenv read (KEY=VALUE, '#' comments, strip quotes)."""
    out: dict[str, str] = {}
    if not path.exists():
        return out
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        out[key.strip()] = value.strip().strip("'\"")
    return out


def _gen() -> str:
    # token_urlsafe -> [A-Za-z0-9_-]; safe in redis://:pass@ and postgres URLs
    # and in docker-compose ${VAR} interpolation (no $, :, @, /, quotes).
    return secrets.token_urlsafe(24)


def ensure_secrets(path: Path, keys=RUNTIME_SECRETS, gen=_gen) -> list[str]:
    """Generate any MISSING key into ``path``. Returns the keys generated."""
    existing = _parse(path)
    missing = [k for k in keys if not existing.get(k)]
    if not missing:
        return []
    block = ["\n# Strong runtime secrets (auto-generated by ensure_secrets.py) "
             "— compose interpolation\n"]
    block += [f"{k}={gen()}\n" for k in missing]
    with path.open("a", encoding="utf-8") as f:
        f.write("".join(block))
    return missing


def load_runtime_env(path: Path, keys=RUNTIME_SECRETS) -> dict[str, str]:
    """Return {key: value} for the runtime secrets present in ``path``.

    Used by the provider to pass these as compose interpolation env (so
    ``${POSTGRES_PASSWORD:-localdev}`` resolves to the strong value, not the
    default).
    """
    parsed = _parse(path)
    return {k: parsed[k] for k in keys if parsed.get(k)}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--path", type=Path,
                        default=Path(__file__).resolve().parent.parent.parent
                        / ".env.secrets")
    args = parser.parse_args(argv)
    try:
        generated = ensure_secrets(args.path)
    except OSError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1
    if generated:
        print(f"[OK] generated strong secrets: {', '.join(generated)}")
    else:
        print("[OK] all runtime secrets already present")
    return 0


if __name__ == "__main__":
    sys.exit(main())
