#!/usr/bin/env python3
"""Render the backend runtime env from the bootstrap state.

After the data-plane bootstrap provisions the least-privilege `facil_app` role
(password lands in deploy/.bootstrap-state.json), this writes
`packages/backend/.env.deploy.gen` with the connection env the backend uses —
so the BACKEND connects as facil_app (DML only) while migrations (db-init) run
as the superuser. Also emits the MinIO SA + OpenBao AppRole for later phases (D3)
when present in the state.

Usage
-----
    python deploy/scripts/render_backend_env.py
    python deploy/scripts/render_backend_env.py --state X --out Y

Exit codes: 0 ok · 1 I/O error.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

DEPLOY_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = DEPLOY_DIR.parent
DEFAULT_STATE = DEPLOY_DIR / ".bootstrap-state.json"
DEFAULT_OUT = REPO_ROOT / "packages" / "backend" / ".env.deploy.gen"


def _state_secrets(state_path: Path) -> dict[str, dict]:
    if not state_path.exists():
        return {}
    data = json.loads(state_path.read_text(encoding="utf-8"))
    return {step["name"]: step.get("secrets", {}) for step in data.get("steps", [])}


def render(state_path: Path = DEFAULT_STATE, *, project: str = "facil",
           host: str = "postgres", port: int = 5432) -> tuple[str, bool]:
    """Build the .env.deploy.gen content. Returns (content, has_db_url)."""
    s = _state_secrets(state_path)
    lines = ["# Generated by render_backend_env.py from .bootstrap-state.json.\n",
             "# DO NOT COMMIT (gitignored). Backend = least-privilege facil_app.\n"]

    pg = s.get("postgres", {})
    role = pg.get("pg_app_role", f"{project}_app")
    pw = pg.get("pg_app_password", "")
    db = pg.get("pg_app_db", project)
    has_url = bool(pw)
    if has_url:
        lines.append(
            f"DATABASE_URL=postgresql+asyncpg://{role}:{pw}@{host}:{port}/{db}\n")

    mi = s.get("minio", {})
    if mi.get("minio_access_key"):
        lines += [f"MINIO_ENDPOINT={mi.get('minio_endpoint', '')}\n",
                  f"MINIO_ACCESS_KEY={mi.get('minio_access_key', '')}\n",
                  f"MINIO_SECRET_KEY={mi.get('minio_secret_key', '')}\n",
                  f"MINIO_BUCKET={mi.get('minio_bucket', '')}\n"]

    ob = s.get("openbao", {})
    if ob.get("openbao_role_id"):
        lines += [f"OPENBAO_ADDR={ob.get('openbao_addr', '')}\n",
                  f"OPENBAO_ROLE_ID={ob.get('openbao_role_id', '')}\n",
                  f"OPENBAO_SECRET_ID={ob.get('openbao_secret_id', '')}\n"]

    return "".join(lines), has_url


# Sentinel that delimits the block this script owns. Everything from the marker
# to EOF is rewritten on each run, so the merge is idempotent.
MANAGED_MARKER = (
    "# --- render_backend_env: bootstrap-derived connection secrets (managed) ---"
)


def _managed_lines(content: str) -> list[str]:
    """The KEY=value lines produced by render() (drops its header comments)."""
    return [
        ln for ln in content.splitlines(keepends=True)
        if "=" in ln and not ln.lstrip().startswith("#")
    ]


def merge_into(existing: str, content: str) -> str:
    """Merge render()'s managed keys into an existing env file.

    render_env.py owns the non-secret config keys (BANGE_*, GEMINI_*, …) and
    writes them to the SAME .env.deploy.gen. This script must ADD the
    bootstrap-derived connection secrets (DATABASE_URL/MINIO_*/OPENBAO_*) without
    clobbering that config — so we preserve every non-managed line and (re)append
    our managed block. Idempotent: re-running drops the prior block first.
    """
    managed = _managed_lines(content)
    if not existing.strip():
        return content  # fresh file: keep render()'s own header + lines

    base = existing.split(MANAGED_MARKER, 1)[0].rstrip("\n")
    managed_keys = {ln.split("=", 1)[0] for ln in managed}
    # Defensive: also drop any stray managed keys left loose in the config body.
    kept = [
        ln for ln in base.splitlines()
        if not ("=" in ln and not ln.lstrip().startswith("#")
                and ln.split("=", 1)[0] in managed_keys)
    ]
    base = "\n".join(kept).rstrip("\n")
    if not managed:
        return base + "\n"
    block = MANAGED_MARKER + "\n" + "".join(managed)
    return base + "\n\n" + block


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--state", type=Path, default=DEFAULT_STATE)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument(
        "--require-db-url", action="store_true",
        help="Fail (exit 1) if no DATABASE_URL could be rendered. Use in "
             "database_mode=local, where the backend depends on facil_app.")
    args = parser.parse_args(argv)
    try:
        content, has_url = render(args.state)
        # Merge into the existing file (render_env.py's config) instead of
        # overwriting it — the two renderers share .env.deploy.gen.
        existing = args.out.read_text(encoding="utf-8") if args.out.exists() else ""
        merged = merge_into(existing, content)
        # newline='\n' => no CRLF on Windows; docker compose env_file stays clean.
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(merged, encoding="utf-8", newline="\n")
    except OSError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1
    if not has_url and args.require_db_url:
        print(f"ERROR: no facil_app password in {args.state} -> no DATABASE_URL "
              f"rendered. The bootstrap's postgres step must succeed first "
              f"(re-run: python deploy/providers/run_bootstrap.py --apply).",
              file=sys.stderr)
        return 1
    note = "" if has_url else "  WARN: no facil_app password in state (run bootstrap first)"
    print(f"[OK] wrote {args.out}{note}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
