"""Partial expression indexes for custom fields — additive DDL only.

The index is PARTIAL (scoped to one organisation) and created CONCURRENTLY, so
it takes no lock and is invisible to other tenants. It is the ONLY DDL SP1 ever
emits at runtime, and it never mutates a column.

`CREATE INDEX CONCURRENTLY` cannot run inside a transaction -> a dedicated
AUTOCOMMIT connection, driven from a background job (see
`app.api.admin_field_definitions`'s `/index` route and `_run_index_build`).

HARD REQUIREMENT: a field is sortable only if `indexed` AND `index_state ==
"ready"` (`sortable_keys` below). `indexed` alone means "the admin asked for
an index" — it says nothing about whether Postgres actually has one yet. A
`pending`/`failed` index means a sequential scan on millions of rows if it
were used for ORDER BY; that must be an explicit 422, never a silent slow
query (see `app.api.list_query.resolve_entity_sort`).

The typed cast (`INDEX_CAST`, types.py) is the whole point: JSONB stores TEXT,
so an untyped `custom_fields->>'rank'` sorts LEXICOGRAPHICALLY ("10" < "9") —
a silent, ERP-fatal bug on a numeric field. The SAME cast expression must
appear in both the index definition (`create_index`, below) and the generated
`ORDER BY` (`custom_sort_column`, below) byte-for-byte, or Postgres will not
use the index and every "indexed" sort silently degrades to a sequential
scan. `custom_sort_column` and `create_index` both format `INDEX_CAST[type]`
from the exact same table — do not let them drift apart.
"""

from __future__ import annotations

import hashlib
import re
from datetime import date, datetime, time
from decimal import Decimal, InvalidOperation
from typing import Any, Callable

from sqlalchemy import Boolean, Date, DateTime, Numeric, String, Time
from sqlalchemy.ext.asyncio import AsyncEngine
from sqlalchemy.sql.elements import ColumnElement
from sqlalchemy.sql.expression import literal_column

from app.core.schema.registry import EXTENSIBLE_TARGETS
from app.core.schema.spec import KEY_RE
from app.core.schema.types import INDEX_CAST, INDEXABLE_TYPES

CUSTOM_FIELD_SORT_PREFIX = "custom_fields."

# Loose UUID-ish shape: FieldDefinition.organization_id is our own DB's
# String(36) PK, always generated by `uuid_str()` — never raw user input
# passed straight through. Checked anyway, as a matter of principle (the
# same one the brief states for the quoting itself): a guard that relies
# entirely on "nothing upstream would ever send something else" is not a
# guard. See `admin_field_definitions._authorize_target` for the actual
# authorization; this is defence in depth against a malformed id reaching
# raw SQL interpolation.
_ORG_ID_RE = re.compile(r"^[a-zA-Z0-9-]{1,36}$")


def index_name(table: str, key: str, organization_id: str) -> str:
    """Deterministic, <=63 chars (Postgres identifier limit — a longer name is
    silently TRUNCATED, which would make two fields collide on one index).

    ORG-SCOPED (CRITICAL fix): the index itself is PARTIAL per organisation
    (`WHERE organization_id = '…'`), but the name used to be derived from
    `(table, key)` alone. Two tenants declaring the same key (a routine
    occurrence — `rank`, `status`, `priority`…) would then share ONE index
    name: org B building `rank` would `DROP INDEX CONCURRENTLY` org A's index
    and recreate it scoped to B, while org A's `FieldDefinition` row still
    said `index_state == "ready"` — every subsequent sort for org A silently
    degraded to a sequential scan, reported as healthy. The name must include
    an org component so two tenants NEVER collide on one index object.

    A short sha1 digest of `organization_id` (not the raw id) keeps the name
    short and identifier-safe regardless of what the id looks like."""
    _assert_safe_org_id(organization_id)
    org_digest = hashlib.sha1(organization_id.encode()).hexdigest()[:8]
    suffix = f"_{org_digest}"
    name = f"ix_{table}_cf_{key}{suffix}"
    if len(name) <= 63:
        return name
    prefix = f"ix_{table}_cf_"
    key_digest = hashlib.sha1(key.encode()).hexdigest()[:8]
    tail = f"_{key_digest}{suffix}"
    budget = max(63 - len(prefix) - len(tail), 0)
    return f"{prefix}{key[:budget]}{tail}"


def sortable_keys(specs: list[dict]) -> set[str]:
    """The sort/filter whitelist. `indexed` alone is NOT enough — the index must
    be READY. A pending index means a seq scan on millions of rows."""
    return {s["key"] for s in specs
            if s.get("indexed") and s.get("index_state") == "ready"}


def _assert_safe_key(key: str) -> None:
    if not KEY_RE.match(key):
        raise ValueError(f"refusing to build SQL for a malformed key {key!r}")


def _assert_safe_org_id(organization_id: str) -> None:
    if not _ORG_ID_RE.match(organization_id):
        raise ValueError(f"refusing to build SQL for a malformed organization_id "
                         f"{organization_id!r}")


class IndexBuildFailed(RuntimeError):
    """Raised when `CREATE INDEX CONCURRENTLY` returns without error but the
    resulting index is INVALID (`pg_index.indisvalid = false`). Postgres can
    do this: a `CONCURRENTLY` build that finds constraint/uniqueness trouble
    only on its second table pass leaves the index object behind, marked
    invalid, rather than raising. `_run_index_build` (admin_field_definitions)
    catches this exactly like any other build failure and sets
    `index_state = "failed"` — it must never be mistaken for success."""


async def index_is_valid(engine: AsyncEngine, target: str, key: str,
                         organization_id: str) -> bool:
    """True iff an index exists under this (target, key, organization_id)'s
    deterministic name AND is VALID. False both when no such index exists and
    when one exists but is INVALID — both mean "not safe to use for a sort".
    Postgres-only; always False elsewhere (SQLite never has a real index to
    check).

    `organization_id` is REQUIRED (CRITICAL fix): the index name is now
    org-scoped (see `index_name`), so checking validity without it would
    either check the wrong tenant's index or silently report False for a
    perfectly valid one."""
    if engine.dialect.name != "postgresql":
        return False
    _assert_safe_key(key)
    name = index_name(EXTENSIBLE_TARGETS[target], key, organization_id)
    autocommit = engine.execution_options(isolation_level="AUTOCOMMIT")
    async with autocommit.connect() as conn:
        row = (await conn.exec_driver_sql(
            "SELECT indisvalid FROM pg_index "
            "JOIN pg_class ON pg_class.oid = pg_index.indexrelid "
            f"WHERE pg_class.relname = '{name}'")).first()
    return bool(row and row[0])


async def create_index(engine: AsyncEngine, target: str, spec: dict,
                       organization_id: str) -> None:
    """Create the partial expression index. Postgres only; a no-op elsewhere
    (SQLite, the test suite) — the repo rule that Postgres-specific SQL is
    guarded by dialect, never emitted blind.

    Genuinely idempotent and self-healing, NOT `CREATE ... IF NOT EXISTS`:
    a FAILED `CREATE INDEX CONCURRENTLY` leaves an INVALID index object under
    the same name (documented Postgres behaviour — see the Postgres manual on
    `CREATE INDEX`: "If a problem arises... the index will be left in an
    invalid state"). `IF NOT EXISTS` is a NAME-ONLY check — the same manual
    warns "there is no guarantee that the existing index is anything like the
    one that would have been created" — so a naive retry over that leftover
    would see the name taken, silently no-op, raise nothing, and the caller
    would report `ready` on an index Postgres refuses to use. Every
    subsequent sort would then silently sequential-scan while the state says
    `ready` — exactly the failure this module exists to prevent.

    So: DROP any leftover first (idempotent, `IF EXISTS` — this is what
    actually clears an INVALID leftover), then CREATE fresh WITHOUT `IF NOT
    EXISTS` (a genuine failure now RAISES instead of being swallowed), then
    VERIFY the result is actually valid (`index_is_valid`) before returning
    normally — a `CONCURRENTLY` build that raises no exception but still
    leaves an INVALID index (see `IndexBuildFailed`) must not be reported as
    success either. Both DDL statements run on the same AUTOCOMMIT
    connection; neither can run inside a transaction.
    """
    if engine.dialect.name != "postgresql":
        return                                   # SQLite (tests) — clean degradation
    ftype, key = spec["type"], spec["key"]
    if ftype not in INDEXABLE_TYPES or ftype not in INDEX_CAST:
        raise ValueError(f"type {ftype!r} cannot be indexed")
    _assert_safe_key(key)
    _assert_safe_org_id(organization_id)

    table = EXTENSIBLE_TARGETS[target]
    expr = INDEX_CAST[ftype].format(key=key)
    name = index_name(table, key, organization_id)
    # organization_id IS interpolated raw here — Postgres DDL cannot bind
    # parameters (no prepared-statement placeholders in CREATE INDEX ... WHERE).
    # Safety comes from `_assert_safe_org_id` above (guarded by `_ORG_ID_RE`),
    # never from quoting alone — quoting a string that could still contain a
    # closing quote would not help.
    autocommit = engine.execution_options(isolation_level="AUTOCOMMIT")
    async with autocommit.connect() as conn:
        await conn.exec_driver_sql(f'DROP INDEX CONCURRENTLY IF EXISTS "{name}"')
        await conn.exec_driver_sql(
            f'CREATE INDEX CONCURRENTLY "{name}" ON "{table}" ({expr}) '
            f"WHERE organization_id = '{organization_id}'")

    if not await index_is_valid(engine, target, key, organization_id):
        raise IndexBuildFailed(
            f"CREATE INDEX CONCURRENTLY {name!r} completed without raising "
            "but the resulting index is INVALID (pg_index.indisvalid=false); "
            "refusing to report it ready")


async def drop_index(engine: AsyncEngine, target: str, key: str,
                     organization_id: str) -> None:
    """Drop the partial expression index (idempotent — `IF EXISTS`). Postgres
    only; a no-op elsewhere. Called on archive (the index becomes non-live —
    the 10-indexed cap deliberately excludes archived rows, so an archived
    field must not keep occupying a live index) and on purge.

    `organization_id` is REQUIRED (CRITICAL fix): without it, this used to
    drop whichever tenant happened to share the (table, key) name — e.g. org
    B purging its `rank` field would delete org A's live, `ready` index too."""
    if engine.dialect.name != "postgresql":
        return
    _assert_safe_key(key)
    name = index_name(EXTENSIBLE_TARGETS[target], key, organization_id)
    autocommit = engine.execution_options(isolation_level="AUTOCOMMIT")
    async with autocommit.connect() as conn:
        await conn.exec_driver_sql(f'DROP INDEX CONCURRENTLY IF EXISTS "{name}"')


# --- Typed sort expression: the SAME cast the index was built with ---------
#
# `app.api.list_query.resolve_entity_sort` accepts `sort=custom_fields.<key>`
# on the entity list endpoints, but ONLY for a key in `sortable_keys(specs)`.
# Once accepted, the generated ORDER BY/keyset predicate must use the exact
# same expression `create_index` indexed, or Postgres silently falls back to
# a sequential scan (the module docstring's hard requirement).

# SQLAlchemy type hints for the cast expressions above — used ONLY for cursor
# encode/decode round-tripping in keyset pagination (`list_query.py`), never
# to generate SQL text (the raw `INDEX_CAST` string is what actually runs).
_SORT_SA_TYPE: dict[str, Any] = {
    "string": String(), "select": String(), "relation": String(),
    "number": Numeric(), "decimal": Numeric(), "money": Numeric(),
    "boolean": Boolean(),
    "date": Date(), "datetime": DateTime(timezone=True), "time": Time(),
}


def custom_sort_column(spec: dict[str, Any]) -> ColumnElement:
    """The ORDER BY / keyset-predicate expression for one custom-field spec —
    byte-for-byte `INDEX_CAST[type]`, the same cast `create_index` used."""
    ftype, key = spec["type"], spec["key"]
    if ftype not in INDEX_CAST:
        raise ValueError(f"type {ftype!r} has no sort cast")
    _assert_safe_key(key)
    return literal_column(INDEX_CAST[ftype].format(key=key),
                          type_=_SORT_SA_TYPE[ftype])


def _to_decimal(raw: Any) -> Decimal | None:
    if raw in (None, ""):
        return None
    try:
        return Decimal(str(raw))
    except InvalidOperation:
        return None


# Parses the JSON representation `validate_blob` wrote (pydantic_gen.py) back
# into the Python value the SQL cast would produce: `decimal` is a decimal
# STRING, `date`/`datetime`/`time` are ISO-8601 strings, everything else
# (string/select/relation/number/boolean) is already JSON-native.
_CUSTOM_VALUE_PARSERS: dict[str, Callable[[Any], Any]] = {
    "string": lambda v: v, "select": lambda v: v, "relation": lambda v: v,
    "number": lambda v: v, "decimal": _to_decimal, "boolean": lambda v: v,
    "date": lambda v: date.fromisoformat(v),
    "datetime": lambda v: datetime.fromisoformat(v),
    "time": lambda v: time.fromisoformat(v),
}


def custom_sort_value(spec: dict[str, Any]) -> Callable[[Any], Any]:
    """Cursor-value extractor for keyset pagination: pulls the same logical
    value the SQL cast produces straight out of the ORM row's already-loaded
    `custom_fields` dict — no extra SELECT column needed to compute the
    keyset cursor's boundary value."""
    ftype, key = spec["type"], spec["key"]
    if ftype == "money":
        def get_money(row: Any) -> Any:
            blob = (getattr(row, "custom_fields", None) or {}).get(key) or {}
            return _to_decimal(blob.get("amount"))
        return get_money

    parser = _CUSTOM_VALUE_PARSERS.get(ftype, lambda v: v)

    def get(row: Any) -> Any:
        raw = (getattr(row, "custom_fields", None) or {}).get(key)
        return parser(raw) if raw is not None else None
    return get
