"""Partial expression indexes for custom fields — additive DDL only.

The index is PARTIAL (scoped to one organisation) and created CONCURRENTLY, so
it takes no lock and is invisible to other tenants. It is the ONLY DDL SP1 ever
emits at runtime, and it never mutates a column.

`CREATE INDEX CONCURRENTLY` cannot run inside a transaction -> a dedicated
AUTOCOMMIT connection, driven from a background job (see
`app.api.admin_field_definitions`'s `/index` route and `_run_index_build`).

HARD REQUIREMENT: a field is sortable only if `indexed` AND `index_state ==
"ready"` (`sortable_keys` below). `indexed` alone means "the admin asked for
an index" — it says nothing about whether Postgres actually has one yet. A
`pending`/`failed` index means a sequential scan on millions of rows if it
were used for ORDER BY; that must be an explicit 422, never a silent slow
query (see `app.api.list_query.resolve_entity_sort`).

The typed cast (`INDEX_CAST`, types.py) is the whole point: JSONB stores TEXT,
so an untyped `custom_fields->>'rank'` sorts LEXICOGRAPHICALLY ("10" < "9") —
a silent, ERP-fatal bug on a numeric field. The SAME cast expression must
appear in both the index definition (`create_index`, below) and the generated
`ORDER BY` (`custom_sort_column`, below) byte-for-byte, or Postgres will not
use the index and every "indexed" sort silently degrades to a sequential
scan. `custom_sort_column` and `create_index` both format `INDEX_CAST[type]`
from the exact same table — do not let them drift apart.
"""

from __future__ import annotations

import hashlib
import re
from datetime import date, datetime, time
from decimal import Decimal, InvalidOperation
from typing import Any, Callable

from sqlalchemy import Boolean, Date, DateTime, Numeric, String, Time
from sqlalchemy.ext.asyncio import AsyncEngine
from sqlalchemy.sql.elements import ColumnElement
from sqlalchemy.sql.expression import literal_column

from app.core.schema.registry import EXTENSIBLE_TARGETS
from app.core.schema.spec import KEY_RE
from app.core.schema.types import INDEX_CAST, INDEXABLE_TYPES

CUSTOM_FIELD_SORT_PREFIX = "custom_fields."

# Loose UUID-ish shape: FieldDefinition.organization_id is our own DB's
# String(36) PK, always generated by `uuid_str()` — never raw user input
# passed straight through. Checked anyway, as a matter of principle (the
# same one the brief states for the quoting itself): a guard that relies
# entirely on "nothing upstream would ever send something else" is not a
# guard. See `admin_field_definitions._authorize_target` for the actual
# authorization; this is defence in depth against a malformed id reaching
# raw SQL interpolation.
_ORG_ID_RE = re.compile(r"^[a-zA-Z0-9-]{1,36}$")


def index_name(table: str, key: str) -> str:
    """Deterministic, <=63 chars (Postgres identifier limit — a longer name is
    silently TRUNCATED, which would make two fields collide on one index)."""
    name = f"ix_{table}_cf_{key}"
    if len(name) <= 63:
        return name
    digest = hashlib.sha1(key.encode()).hexdigest()[:8]
    return f"ix_{table}_cf_{key[:63 - len(f'ix_{table}_cf_') - 9]}_{digest}"


def sortable_keys(specs: list[dict]) -> set[str]:
    """The sort/filter whitelist. `indexed` alone is NOT enough — the index must
    be READY. A pending index means a seq scan on millions of rows."""
    return {s["key"] for s in specs
            if s.get("indexed") and s.get("index_state") == "ready"}


def _assert_safe_key(key: str) -> None:
    if not KEY_RE.match(key):
        raise ValueError(f"refusing to build SQL for a malformed key {key!r}")


def _assert_safe_org_id(organization_id: str) -> None:
    if not _ORG_ID_RE.match(organization_id):
        raise ValueError(f"refusing to build SQL for a malformed organization_id "
                         f"{organization_id!r}")


async def create_index(engine: AsyncEngine, target: str, spec: dict,
                       organization_id: str) -> None:
    """Create the partial expression index. Postgres only; a no-op elsewhere
    (SQLite, the test suite) — the repo rule that Postgres-specific SQL is
    guarded by dialect, never emitted blind."""
    if engine.dialect.name != "postgresql":
        return                                   # SQLite (tests) — clean degradation
    ftype, key = spec["type"], spec["key"]
    if ftype not in INDEXABLE_TYPES or ftype not in INDEX_CAST:
        raise ValueError(f"type {ftype!r} cannot be indexed")
    _assert_safe_key(key)
    _assert_safe_org_id(organization_id)

    table = EXTENSIBLE_TARGETS[target]
    expr = INDEX_CAST[ftype].format(key=key)
    name = index_name(table, key)
    # organization_id is a UUID string from our own DB, never user input — but it
    # is still quoted, never interpolated raw, as a matter of principle.
    sql = (f'CREATE INDEX CONCURRENTLY IF NOT EXISTS "{name}" ON "{table}" ({expr}) '
           f"WHERE organization_id = '{organization_id}'")

    autocommit = engine.execution_options(isolation_level="AUTOCOMMIT")
    async with autocommit.connect() as conn:
        await conn.exec_driver_sql(sql)


async def drop_index(engine: AsyncEngine, target: str, key: str) -> None:
    """Drop the partial expression index (idempotent — `IF EXISTS`). Postgres
    only; a no-op elsewhere. Called on archive (the index becomes non-live —
    the 10-indexed cap deliberately excludes archived rows, so an archived
    field must not keep occupying a live index) and on purge."""
    if engine.dialect.name != "postgresql":
        return
    _assert_safe_key(key)
    name = index_name(EXTENSIBLE_TARGETS[target], key)
    autocommit = engine.execution_options(isolation_level="AUTOCOMMIT")
    async with autocommit.connect() as conn:
        await conn.exec_driver_sql(f'DROP INDEX CONCURRENTLY IF EXISTS "{name}"')


# --- Typed sort expression: the SAME cast the index was built with ---------
#
# `app.api.list_query.resolve_entity_sort` accepts `sort=custom_fields.<key>`
# on the entity list endpoints, but ONLY for a key in `sortable_keys(specs)`.
# Once accepted, the generated ORDER BY/keyset predicate must use the exact
# same expression `create_index` indexed, or Postgres silently falls back to
# a sequential scan (the module docstring's hard requirement).

# SQLAlchemy type hints for the cast expressions above — used ONLY for cursor
# encode/decode round-tripping in keyset pagination (`list_query.py`), never
# to generate SQL text (the raw `INDEX_CAST` string is what actually runs).
_SORT_SA_TYPE: dict[str, Any] = {
    "string": String(), "select": String(), "relation": String(),
    "number": Numeric(), "decimal": Numeric(), "money": Numeric(),
    "boolean": Boolean(),
    "date": Date(), "datetime": DateTime(timezone=True), "time": Time(),
}


def custom_sort_column(spec: dict[str, Any]) -> ColumnElement:
    """The ORDER BY / keyset-predicate expression for one custom-field spec —
    byte-for-byte `INDEX_CAST[type]`, the same cast `create_index` used."""
    ftype, key = spec["type"], spec["key"]
    if ftype not in INDEX_CAST:
        raise ValueError(f"type {ftype!r} has no sort cast")
    _assert_safe_key(key)
    return literal_column(INDEX_CAST[ftype].format(key=key),
                          type_=_SORT_SA_TYPE[ftype])


def _to_decimal(raw: Any) -> Decimal | None:
    if raw in (None, ""):
        return None
    try:
        return Decimal(str(raw))
    except InvalidOperation:
        return None


# Parses the JSON representation `validate_blob` wrote (pydantic_gen.py) back
# into the Python value the SQL cast would produce: `decimal` is a decimal
# STRING, `date`/`datetime`/`time` are ISO-8601 strings, everything else
# (string/select/relation/number/boolean) is already JSON-native.
_CUSTOM_VALUE_PARSERS: dict[str, Callable[[Any], Any]] = {
    "string": lambda v: v, "select": lambda v: v, "relation": lambda v: v,
    "number": lambda v: v, "decimal": _to_decimal, "boolean": lambda v: v,
    "date": lambda v: date.fromisoformat(v),
    "datetime": lambda v: datetime.fromisoformat(v),
    "time": lambda v: time.fromisoformat(v),
}


def custom_sort_value(spec: dict[str, Any]) -> Callable[[Any], Any]:
    """Cursor-value extractor for keyset pagination: pulls the same logical
    value the SQL cast produces straight out of the ORM row's already-loaded
    `custom_fields` dict — no extra SELECT column needed to compute the
    keyset cursor's boundary value."""
    ftype, key = spec["type"], spec["key"]
    if ftype == "money":
        def get_money(row: Any) -> Any:
            blob = (getattr(row, "custom_fields", None) or {}).get(key) or {}
            return _to_decimal(blob.get("amount"))
        return get_money

    parser = _CUSTOM_VALUE_PARSERS.get(ftype, lambda v: v)

    def get(row: Any) -> Any:
        raw = (getattr(row, "custom_fields", None) or {}).get(key)
        return parser(raw) if raw is not None else None
    return get
